name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-app:latest .

      - name: Exécuter Docker Scout (analyse des vulnérabilités)
        run: |
          docker scout quickview ${{ secrets.DOCKER_USERNAME }}/voting-app:latest

      - name: Pousser l'image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/voting-app:latest
